generator:
  target: "model.hififace.Generator"
  params:
    identity_extractor_config:
      f_3d_checkpoint_path: "./model/Deep3DFaceRecon_pytorch/checkpoints/epoch_20.pth"
      f_id_checkpoint_path: "./model/Deep3DFaceRecon_pytorch/checkpoints/ms1mv3_arcface_r100_fp16_backbone.pth"

  optimizer:
    target: "torch.optim.AdamW"
    params:
      lr: 1e-4
      betas: 
      - 0
      - 0.999

discriminator:
  target: "model.multiscalediscriminator.MultiscaleDiscriminator"
  params:
    input_nc: 3

  optimizer:
    target: "torch.optim.AdamW"
    params:
      lr: 1e-4
      betas: 
      - 0
      - 0.999

g_loss:
  target: "model.loss.GLoss"
  params:
    f_3d_checkpoint_path: "./model/Deep3DFaceRecon_pytorch/checkpoints/epoch_20.pth"
    f_id_checkpoint_path: "./model/Deep3DFaceRecon_pytorch/checkpoints/ms1mv3_arcface_r100_fp16_backbone.pth"
    sid_config:
      {}
    realism_config:
      {}

d_loss:
  target: "model.loss.DLoss"
  params: {}

dataset:
  train:
    target: "dataset.HifiFaceParsingTrainDataset"
    params:
      img_root: "./vggface2/vggface2_224_subset"
      parsing_root: "./vggface2/vggface2_crop_arcfacealign_224_aligned"
      same_rate: 50
    dataloader:
      batch_size: 4
      num_workers: 32
      drop_last: True
      shuffle: True

  validation:
    target: "dataset.HifiFaceParsingValDataset"
    params:
      img_root: "./vggface2/vggface2_subset_val"
      parsing_root: "./vggface2/vggface2_subset_parse_val"
    dataloader:
      batch_size: 1
      shuffle: False
      num_workers: 8
