checkpoint:
  save_dir: "./checkpoint_save_dir"
  callback:
    monitor: "validation / g_loss"
    save_top_k: -1
    verbose: True
    every_n_train_steps: 40000

wandb:
  project: "hififace"
  entity: "marcocheung"

trainer:
  gradient_clip_val: 0
  max_epochs: 1000
  num_sanity_val_steps: 1
  fast_dev_run: False
  val_check_interval: 400
  benchmark: True
